"""initial_tables

Revision ID: df25084a0143
Revises: 
Create Date: 2026-04-28 08:21:15.835940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df25084a0143'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False, comment='원본 문서 ID'),
    sa.Column('domain_name', sa.String(length=120), nullable=True),
    sa.Column('source_spec', sa.String(length=512), nullable=True),
    sa.Column('creation_year', sa.String(length=10), nullable=True),
    sa.Column('chunk_idx', sa.Integer(), nullable=False, comment='청크 순번'),
    sa.Column('text_preview', sa.String(length=512), nullable=True, comment='첫 512자 미리보기'),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=False)
    op.create_index(op.f('ix_documents_domain_name'), 'documents', ['domain_name'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.Text(), nullable=False, comment='사용자 입력 질문'),
    sa.Column('domain', sa.String(length=120), nullable=True, comment='요청 도메인(과) 필터'),
    sa.Column('used_collection', sa.String(length=120), nullable=True, comment='실제 사용된 컬렉션명'),
    sa.Column('answer', sa.Text(), nullable=True, comment='반환된 답변 텍스트'),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=40), nullable=True, comment='사용된 LLM 제공자'),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='질의 시각(UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_id'), 'query_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_logs_id'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_domain_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
